language: python
python:
  - '3.7'

dist:
  bionic

services:
  docker

env:
  - REACT_APP_API_URL=http://localhost:5001 DATABASE_URL=postgresql://postgres:postgres@db:5432/video_reuse_detector_dev DATABASE_TEST_URL=postgresql://postgres:postgres@db:5432/video_reuse_detector_test

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y ffmpeg; fi

install:
  - 'pip install pipenv'
  - 'pipenv install --dev'

script:
  - 'make check'
  - 'make build-images'
  - 'make run-containers'
  - 'make test'
