language: python
python:
  - '3.7'

services:
  docker

env:
  - REACT_APP_API_URL=http://localhost:5001 DATABASE_URL=postgresql://postgres:postgres@db:5432/video_reuse_detector_dev DATABASE_TEST_URL=postgresql://postgres:postgres@db:5432/video_reuse_detector_test

install:
  - 'pip install pipenv'
  - 'pipenv install --dev'

script:
  - 'make build-images'
  - 'make run-containers'
  - 'make check'
