language: python
python:
  - '3.7'

dist:
  bionic

services:
  docker

env:
  - REACT_APP_API_URL=http://localhost:5001 DATABASE_URL=postgresql://postgres:postgres@db:5432/video_reuse_detector_dev DATABASE_TEST_URL=postgresql://postgres:postgres@db:5432/video_reuse_detector_test

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y ffmpeg npm; fi

install:
  - 'pip install pipenv'
  - 'pipenv install --dev'
  - script: 'npm install --prefix frontend'

jobs:
  include:
    - script: make lint-check
      name: "Lint Checks"
    - script: make mypy-check
      name: "Type Checks"
    - script: make unit-test
      name: "Unit Tests"
    - script: make smoke-test
      name: "Smoke Tests"
    - stage: "App Tests"
    - script: docker-compose up --scale extractor=4 --scale comparator=4 --build -d
      name: "Deploy"
    - script: make middleware-test
      name: "Test"
