language: python
python:
  - '3.7'

services:
  docker

env:
  - REACT_APP_API_URL=http://localhost:5001

install:
  - 'pip install pipenv'
  - 'pipenv install --dev'

script:
  - 'make build-images'
  - 'make run-containers'
  - 'make check'
