version: '3.7'

x-uploads_volume:
  &uploads_volume
  type: bind
  source: ./static/videos/uploads
  target: /usr/src/app/static/videos/uploads

x-archive_volum:
  &archive_volume
  type: bind
  source: ./static/videos/archive
  target: /usr/src/app/static/videos/archive

services:
  middleware:
    build:
      context: ./
      dockerfile: ./middleware/Dockerfile
    entrypoint: ["docker-entrypoint.sh"]
    expose:
      - 5000
    ports:
      - 5001:5000
    volumes:
      - './middleware:/usr/src/app/middleware'
      - './video_reuse_detector:/usr/src/app/video_reuse_detector'
      - *archive_volume
      - *uploads_volume
    env_file:
      ./.env.dev
    environment:
      # Should NOT contain the trailing /api
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - db

  comparator:
    image: video_reuse_detector_middleware
    command: python -m middleware.manage run_comparator
    volumes:
      - './middleware:/usr/src/app/middleware'
      - './video_reuse_detector:/usr/src/app/video_reuse_detector'
      - *archive_volume
      - *uploads_volume
    env_file:
      - ./.env.dev
    depends_on:
      - redis

  extractor:
    image: video_reuse_detector_middleware
    command: python -m middleware.manage run_extractor
    volumes:
      - './middleware:/usr/src/app/middleware'
      - './video_reuse_detector:/usr/src/app/video_reuse_detector'
      - *archive_volume
      - *uploads_volume
    env_file:
      - ./.env.dev
    depends_on:
      - redis

  redis:
    image: redis:4.0.11-alpine

  db:
    build:
      context: ./middleware/db
      dockerfile: Dockerfile
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

  dashboard:
    build: ./dashboard
    image: dashboard
    container_name: dashboard
    ports:
      - '9181:9181'
    command: rq-dashboard -H redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./.env.dev
    depends_on:
      - middleware

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8082:8080
    volumes:
      - *archive_volume
      - *uploads_volume
    depends_on:
      - middleware
      - frontend

volumes:
  postgres_data:
