version: '3.7'

services:
  notebook:
    build:
      context: ./
      dockerfile: ./notebooks/Dockerfile
    ports:
      - 8085:8888
    volumes:
      - 'notebooks:/home/jovyan/work'
      - './static:/home/jovyan/work/static'
      - './video_reuse_detector:/home/jovyan/work/video_reuse_detector'
    command: "start-notebook.sh \
        --NotebookApp.password=${ACCESS_TOKEN}"
    environment:
      - VIDEO_DIRECTORY=/home/jovyan/work/static/videos/archive
      - IMAGES_DIRECTORY=/home/jovyan/work/static/images

volumes:
  notebooks:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/notebooks
