version: '3.7'

services:
  notebook:
    build:
      context: ./
      dockerfile: ./notebooks/Dockerfile
    ports:
      - 8085:8888
    volumes:
      - './notebooks:/home/jovyan/work'
      - './static:/home/jovyan/work/static'
      - './video_reuse_detector:/home/jovyan/work/video_reuse_detector'
    command: "start-notebook.sh \
        --NotebookApp.password=${ACCESS_TOKEN}"
    environment:
      - VIDEO_DIRECTORY=/home/jovyan/work/static/videos/archive
      - BENCHMARKS_DIRECTORY=/home/jovyan/work/benchmarks
      - OUTPUT_DIRECTORY=/home/jovyan/work/out
      - INTERIM_DIRECTORY=/home/jovyan/work/interim
      # Note: should include trailing /api
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - LOGURU_LEVEL=INFO
